### ISSUE TITLE
[Feature 9] Tile Entity

### ISSUE THREAD

**Issue by JLenander** [CSC207-2022F-UofT/course-project-monopolymen#10]
Every Tile is a space on the board that can be landed on. This feature encapsulates all of the tiles that exist in the game.

**Comment by JLenander** [comment]
Note that Tile and Property had to be changed to abstract methods from interfaces because of their instance attributes.

**Comment by JLenander** [comment]
@SDunk1011 bd6e0f9 There is no need for Income and Luxury tax to be different classes, they can be constructed with a `taxAmount` attribute that specifies the amount of income tax (especially since we agreed on using post-2008 rules)

Also, there shouldn't be any form of UI interaction with the player like the print statements and the scanner in these entity classes.

**Comment by iamyanbo** [comment]
JailTile and GoToJailTile has different returns than other tiles (instead of flavorText its a player instance) as they require different logic such as move player and figure out what to do in jail.

**Comment by JLenander** [comment]
Still needed:
DrawCardTile
Implementation Specific changes using the proper getters from other classes
