### ISSUE TITLE
[Feature 4] Viewing Player Statistics Profile

### ISSUE THREAD

**Issue by Youssefb1234** [CSC207-2022F-UofT/course-project-monopolymen#2]
A player should have a profile keeping track of statistics such as their win rate. This profile can be accessed by logging in to the profile page when a game is not currently being played. Every player has a PlayerStats class, and during every turn, the UpdateStats method will be called, and the instance attributes of player information will be taken the last time updatestats method is called. The SavePlayerStats class will save player stats (by checking if it exists first) from the PlayerStats object into a file. The class LoadPlayerStats will then load all of the information from the file into a PlayerStats instance. (YB)

**Comment by JLenander** [comment]
Dropped feature to focus on more core monopoly parts
