### ISSUE TITLE
[Feature 6] Trading

### ISSUE THREAD

**Issue by colewiltse** [CSC207-2022F-UofT/course-project-monopolymen#4]
When it is a player’s turn, after they roll the dice, they will have a trade button on their
screen that they can click on. When that happens, the GameState class calls a method
in the Turn class which then calls the MakeOffer method from the Trade class. Then, the
player who wants to make a trade specifies who they want to trade with, what properties
they are willing to give up and what properties they want in return. The properties they
can choose from are chosen from an instance of the TradeOption class which stores
what properties among the two players are available to trade. Also, the actual details of
the trade offer such as the properties that are in the trade offer and the money involved
are put into an instance of the TradeOffer class. The player receiving the trade offer
then is given the option to either accept the trade, make a counter offer, or decline the
trade. Accepting the trade calls the ExecuteOffer method from the Trade class that
updates each player’s inventory that was involved with the trade. Making a counter offer
calls the MakeOffer method again, only with the two player’s roles in the trade reversed.
Declining the offer simply ends the function with neither of the players’ inventory
updated.

**Comment by iamyanbo** [comment]
This Use Case will need to implement from its input boundary, see [this example](https://github.com/paulgries/UserLoginCleanArchitecture/tree/main/src/user_register_use_case)

**Comment by colewiltse** [comment]
It is already implemented
