### ISSUE TITLE
[Feature 5] Saving and Loading Game State

### ISSUE THREAD

**Issue by SDunk1011** [CSC207-2022F-UofT/course-project-monopolymen#5]
Once a player is created, the current game statement of this player would be saved in a file (xml or json) by the save method in SaveGameState class, which may be accomplished by a java package called dom4j. The file would include the info of this player and game state data, such as the name of the player and the property of the player. Besides, players are allowed to load the game that was saved before by the load method in the LoadGameState class.

**Comment by JLenander** [comment]
Completed with 73547177905de2ba596406ed113506621e362a9d
