### ISSUE TITLE
[Feature 15] Game State

### ISSUE THREAD

**Issue by JLenander** [CSC207-2022F-UofT/course-project-monopolymen#52]
Game State keeps track of all entities in a game and any miscellaneous attributes of a game (ex. turn order)
Game State is logistically responsible for switching between player turns.

**Comment by TahirLeonenko** [comment]
The logic for the if statement on giving the option to leave jail in game state (line 92), needs to be changed so that it's if turnsInJail is over -1 instead of equal.

**Comment by TahirLeonenko** [comment]
GameState will need a method that removes a given player from the GameState's players. It will also need to be able to appropriately handle the players list shortening and currentPlayer staying the same number  while still making the next player start it's turn.
