### ISSUE TITLE
[Feature 7] Player Entity 

### ISSUE THREAD

**Issue by alirezazim03** [CSC207-2022F-UofT/course-project-monopolymen#7]
The Player is a Class responsible for keeping track of each player's inventory, position, money, and all other related attributes. It also includes methods that help update this information.

**Comment by iamyanbo** [comment]
Player will need to implement a way to check if they own a "get out of jail" card, perhaps a private attribute HasGetOutOfjailCard and a getter method. Also, check spelling for some method headers.
