### ISSUE TITLE
[Feature 15] Add Game State functionality to remove player from play

### ISSUE THREAD

**Issue by TahirLeonenko** [CSC207-2022F-UofT/course-project-monopolymen#79]
GameState will need a method that removes a given player (player that has been bankrupted) from the GameState's players. It will also need to be able to appropriately handle the players list shortening and currentPlayer staying the same number while still making the next player start it's turn.

**Comment by JLenander** [comment]
Added in 4523a3e99590532c798e0781278f3a7ac84e5724
