### ISSUE TITLE
[Feature 8] Board Entity

### ISSUE THREAD

**Issue by TahirLeonenko** [CSC207-2022F-UofT/course-project-monopolymen#8]

**Comment by TahirLeonenko** [comment]
Creating the basic structure for the board class

**Comment by iamyanbo** [comment]
Board needs implementation to get position of a tile, perhaps a method GetTilePosition. For example: the "go to jail" tile will move the player to the "jail" tile. The tile action needs to know where to move the player.

**Comment by TahirLeonenko** [comment]
getTilePosition function added to board class. May be changed based on whether the function needs to compare tileName or tileDisplayName
