### ISSUE TITLE
[TradeUseCase Can Trade Properties With Houses]

### ISSUE THREAD

**Issue by TahirLeonenko** [CSC207-2022F-UofT/course-project-monopolymen#82]
In the TradeOffer class, the checkPropertiesRecieved/Offered only checks whether the player owns the property. Players also cannot trade properties if any of the color properties have houses on them (even if you sell a colorProperty that doesn't have a house on it, you need to make sure that the other colorPropertys that the player owns doesn't have houses on them.

**Comment by colewiltse** [comment]
Fixed it!
